---
- hosts: all
  gather_facts: false

  vars_prompt:
  - name: username
    prompt: "Enter username"
    private: no
  - name: password
    prompt: "Enter password"
  - name: domain_name
    prompt: "Enter domain name"
    private: no
  - name: netbios_name
    prompt: "Enter NetBIOS name"
    private: no
  - name: safe_mode_pw
    prompt: "Enter safe mode password"

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: Create new domain in a new forest on the target host
    ansible.windows.win_domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ safe_mode_pw }}"

  - name: Create new Windows domain in a new forest with specific parameters
    ansible.windows.win_domain:
      create_dns_delegation: no
      database_path: C:\Windows\NTDS
      dns_domain_name: "{{ domain_name }}"
      domain_netbios_name: "{{ netbios_name }}"
      safe_mode_password: "{{ safe_mode_pw }}"
      sysvol_path: C:\Windows\SYSVOL
    register: domain_install
